### ISSUE TITLE
How to disable default apiServer.admissionControl policy

### ISSUE THREAD

**Issue by den-is** [siderolabs/terraform-provider-talos#163]
I'm trying to disable default PodSecurityAdmission policy, so kindly enabled by the Talos team.

I've tried to pass empty array value to plain yaml configuration.
```hcl
yamlencode({
    cluster = {
      apiServer = {
        admissionControl = []
      }
      # omitted
    }
    # omitted
}
```
Tried to apply actual patchesJson6902 patch (which works for my test/non-tf deploys)
```yaml
- op: replace
  path: /cluster/apiServer/admissionControl
  value: []
```
```hcl
data "talos_machine_configuration" "controlplane" {
  # omitted
  config_patches = [
    local.controlplane_config_patch,
    file("${path.module}/patches/disable-pod-security-admission.yaml")
  ]
}
```
Nothing seems to be working, except manually removing it using talosctl.
Each time I reapply terrafrom policy returns.

**Comment by smira** [comment]
There is no easy way at the moment with strategic merge patches, but you can use a partial patch to change all policies to 'privileged' which will effectively disable it.

**Comment by den-is** [comment]
@smira wrong answer :)

Strategic Merge Patch indeed is not working, but JSON Patch (RFC6902) did actually work.

My bad. I pushed an empty patch file. After actually providing:
```yaml
- op: replace
  path: /cluster/apiServer/admissionControl
  value: []
```
Everything worked
