### ISSUE TITLE
Better way to see why inline manifests are failing to apply?

### ISSUE THREAD

**Issue by districtofpaige** [siderolabs/terraform-provider-talos#223]
Hello, I love the provider being able to robustly bootstrap a talos cluster. I am trying to bootstrap a number of kubernetes manifests as well to get key cluster resources created -- however I find that many of the manifests I add to the inline manifests array do not get deployed. I'm sure there could be some sort of user error but is there a place where this gets reported?

I think of the inline manifests I've tried it will create namespaces but then none of the other resources I specify in my config -- is there a log source that will tell me why they are failing to apply?

```
cluster:
        externalCloudProvider:
            enabled: true
            manifests:
                - https://raw.githubusercontent.com/sergelogvinov/proxmox-csi-plugin/main/docs/deploy/proxmox-csi-plugin.yml
                - https://raw.githubusercontent.com/sergelogvinov/proxmox-cloud-controller-manager/main/docs/deploy/cloud-controller-manager.yml
        inlineManifests:
            - name: csi-namespace
              contents: |4
                        apiVersion: v1
                        kind: Namespace
                        metadata:
                          name: csi-proxmox
                          labels:
                            pod-security.kubernetes.io/enforce=privileged
            - name: argo-namespace
              contents: |4
                        apiVersion: v1
                        kind: Namespace
                        metadata:
                          name: argocd
            - name: gitea-namespace
              contents: |4
                        apiVersion: v1
                        kind: Namespace
                        metadata:
                          name: gitea
            - name: proxmox-cloud-controller-manager
              contents: |4
                        apiVersion: v1
                        kind: Secret
                        type: Opaque
                        metadata:
                          name: proxmox-cloud-controller-manager
                          namespace: kube-system
                        stringData:
                          config.yaml: |
                            clusters:
                              - url: <hostname>
                                insecure: false
                                token_id: "<tokenid>"
                                token_secret: <secret>
                                region: Region-1
            - name: test-secret
              contents: |4
                        apiVersion: v1
                        kind: Secret
                        type: Opaque
                        metadata:
                          name: test-secret
                          namespace: csi-proxmox
                        data:
                          username: username
                          password: fake_password_test
            - name: proxmox-csi-plugin
              contents: |4
                        apiVersion: v1
                        kind: Secret
                        type: Opaque
                        metadata:
                          name: proxmox-csi-plugin
                          namespace: csi-proxmox
                        stringData:
                          config.yaml: |
                            clusters:
                              - url: <hostname>
                                insecure: false
                                token_id: "<tokenid>"
                                token_secret: <secret>
                                region: Region-1
            - name: ZFS SC
              contents: |4
                      allowVolumeExpansion: true
                      apiVersion: storage.k8s.io/v1
                      kind: StorageClass
                      metadata:
                        name: proxmox-data-zfs
                      parameters:
                        csi.storage.k8s.io/fstype: zfs
                        ssd: "true"
                        storage: local-zfs
                      provisioner: csi.proxmox.sinextra.dev
                      reclaimPolicy: Delete
                      volumeBindingMode: WaitForFirstConsumer
        allowSchedulingOnControlPlanes: true
```
